name: Build & Test PIUIO kernel module

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        # “native” = headers that ship with the runner’s own kernel
        kver: [native, '5.15.0-92-generic', '6.2.0-39-generic']

    steps:
      - uses: actions/checkout@v4

      # figure-out which header revision to pull in this matrix slot
      - name: Pick kernel version
        id: kver
        run: |
          if [ "${{ matrix.kver }}" = "native" ]; then
            echo "ver=$(uname -r)" >>"$GITHUB_OUTPUT"
          else
            echo "ver=${{ matrix.kver }}" >>"$GITHUB_OUTPUT"
          fi

      - name: Install tool-chain & headers
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends \
               build-essential bc sparse \
               linux-headers-${{ steps.kver.outputs.ver }}

      # run checkpatch only once (native kernel slot)
      - name: checkpatch (style only)
        if: matrix.kver == 'native'
        run: |
          curl -sL https://raw.githubusercontent.com/torvalds/linux/master/scripts/checkpatch.pl \
               -o checkpatch.pl
          chmod +x checkpatch.pl
          ./checkpatch.pl --no-tree -f mod/*.c || true

      - name: Build with sparse
        working-directory: mod
        run: |
          make -C /lib/modules/${{ steps.kver.outputs.ver }}/build \
               M=$PWD C=2 CHECK=sparse modules

      - name: Show module info
        run: |
          modinfo mod/piuio.ko

      # smoke-test only on the runner’s own kernel
      - name: Load / unload module (native only)
        if: matrix.kver == 'native'
        run: |
          sudo insmod mod/piuio.ko
          sleep 1
          sudo rmmod piuio