name: Build and Test PIUIO Kernel Module

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kernel_version:
          - $(uname -r) # Native kernel
          - 6.2.0-39-generic
          - 5.15.0-92-generic

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential kmod libelf-dev sparse linux-source \
            linux-headers-${{ matrix.kernel_version }}

      - name: Kernel Coding Style Check
        run: |
          cp /usr/src/linux-source-*/scripts/checkpatch.pl .
          ./checkpatch.pl --strict mod/*.c mod/*.h

      - name: Static Analysis with Sparse
        run: |
          make -C /usr/src/linux-headers-${{ matrix.kernel_version }} M="$PWD/mod" C=2 CHECK=sparse modules

      - name: Build Module for Kernel ${{ matrix.kernel_version }}
        working-directory: mod
        run: |
          make -C /usr/src/linux-headers-${{ matrix.kernel_version }} M="$PWD" modules

      - name: modinfo Sanity Check
        run: |
          modinfo ./mod/piuio_hid.ko

      - name: Load/Unload Test with Error Check (Native kernel only)
        if: matrix.kernel_version == '$(uname -r)'
        run: |
          sudo insmod ./mod/piuio_hid.ko || (sudo dmesg | tail -n50 && exit 1)
          sleep 2
          sudo dmesg | tail -n50 | grep -Ei "(BUG|panic|oops|warn|error)" && exit 1 || echo "No critical errors"
          sudo rmmod piuio_hid

