name: Build & Smoke-test PIUIO

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  smoke-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Updated this step to include libselinux-dev
      - name: Install dependencies
        run: |
          sudo apt-get update
          # Install kernel headers AND selinux development files
          sudo apt-get install -y linux-headers-generic libselinux-dev

      - name: Set kernel version
        id: set-kver
        run: echo "KVER=$(ls /lib/modules | grep -v azure | head -n1)" >> $GITHUB_ENV

      # This step prepares the kernel headers using 'make scripts'
      - name: Prepare kernel headers
        run: sudo make -C /lib/modules/${{ env.KVER }}/build scripts

      # This step builds your actual module using your Makefile
      - name: Build module
        working-directory: mod
        run: make KVER=$KVER

      - name: Smoke-test install
        working-directory: mod
        run: |
          sudo make KVER=$KVER install
          # Check if module is loaded after install
          lsmod | grep piuio_hid

      - name: Smoke-test uninstall
        working-directory: mod
        run: |
          sudo make KVER=$KVER uninstall
          # Check if module is NOT loaded after uninstall (grep should fail)
          ! lsmod | grep piuio_hid

